AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Order flowers, using Amazon Lex to perform natural language understanding'
Resources:
  ordersandich:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: >-
        Order flowers, using Amazon Lex to perform natural language
        understanding
      MemorySize: 128
      Timeout: 10
      Role: 'arn:aws:iam::563132285289:role/amplify-login-lambda-7672514d'
      Tags:
        'lambda-console:blueprint': lex-order-flowers-python
